# -*- python -*- 

env = Environment(CXXFLAGS=['-g', '-O2', '-ansi', '-pedantic', '-Wall', '-Werror'], CPPPATH=['../src'])
# env.ParseConfig("sdl-config --cflags --libs")
env.Program('tinygettext', ['tinygettext.cpp', '../src/libtinygettext.a'])
env.Program('po_parser_test', ['po_parser_test.cpp', '../src/libtinygettext.a'])

# EOF #
