# -*- python -*-

env = Environment(CXXFLAGS=['-g', '-O0', '-ansi', '-pedantic', '-Wall', '-Werror'])
env.ParseConfig("sdl-config --cflags --libs")
env.StaticLibrary('tinygettext', 
                  ['tinygettext.cpp',
                   'language.cpp',
                   'dictionary.cpp',
                   'dictionary_manager.cpp',
                   'directory.cpp',
                   'po_parser.cpp',
                   'iconv.cpp',
                   'log.cpp'])


# EOF #
